<?php
return [
    'internalBks' => [
        'extension' => 'Not BK',
        'onewin' => '1Win',
        'onexbet' => '1xBet',
        'onexbit' => '1xBit',
        'onexstavka' => '1xstavka',
        'sevenbet' => '7bet',
        'sport888' => '888sport',
        'astekbet' => 'Astekbet',
        'batery' => 'Batery',
        'baterymobile' => 'Batery.Mobile',
        'bcgame' => 'Bcgame',
        'bet365' => 'Bet365',
        'bet365au' => 'Bet365 AU',
        'bet365it' => 'Bet365 Italy (EE)',
        'bet365test' => 'Bet365 test',
        'bet365es' => 'Bet365ES',
        'bet365gr' => 'Bet365gr',
        'bet365kz' => 'Bet365mx',
        'be365ru' => 'Bet365ru',
        'betandyou' => 'Betandyou',
        'betboom' => 'Betboom',
        'betboomcom' => 'BetboomCom',
        'betcityby' => 'Betcity Belarus',
        'betcity' => 'Betcity Cupis',
        'betfair' => 'BetFair',
        'betfaires' => 'BetfairES',
        'betflip' => 'Betflip',
        'betfury' => 'Betfury',
        'betiro' => 'Betiro',
        'betpanda' => 'Betpanda',
        'betplay' => 'Betplay',
        'betsafe' => 'Betsafe',
        'betsson' => 'Betsson',
        'betvictor' => 'BetVictor',
        'betway' => 'Betway',
        'betwaybe' => 'BetwayBE',
        'betwinner' => 'Betwinner',
        'bitz' => 'Bitz',
        'bookmaker' => 'Bookmaker',
        'bwin' => 'BWin',
        'bwinbe' => 'BWinBE',
        'bwincupis' => 'bwin cupis',
        'campobet' => 'Campobet',
        'casinowinner' => 'CasinoWinner',
        'chipsgg' => 'ChipsGG',
        'coinplay' => 'Coin Play',
        'coinsgame' => 'Coinsgame',
        'crashino' => 'Crashino',
        'cryptocasino' => 'Cryptocasino',
        'csgo500' => 'Csgo500',
        'dafabet' => 'Dafa Bet',
        'dbbet' => 'Dbbet',
        'duel' => 'Duel',
        'fairspin' => 'Fairspin',
        'fansport' => 'Fansport',
        'favbet' => 'Favbet',
        'fonru' => 'Fon.Ru',
        'fonbet' => 'Fonbet',
        'fonbetcupis' => 'Fonbet.Cupis',
        'fonbetby' => 'FonbetBY',
        'foncupismobile' => 'Fonbetcupis.Mobile',
        'fonbetgr' => 'FonbetGR',
        'fonbetkz' => 'FonbetKZ',
        'fortunejack' => 'Fortunejack',
        'gamdom' => 'Gamdom',
        'jetbull' => 'Gamdomm',
        'gamebookers' => 'Gamebookers',
        'grosvenor' => 'Grosvenor',
        'ivibet' => 'Ivibet',
        'jbcom' => 'Jbcom',
        'jetton' => 'Jetton',
        'justbit' => 'Justbit',
        'ladbrokes' => 'LadBrokes',
        'leon' => 'Leon',
        'leoncupis' => 'Leon Cupis',
        'ligastavok' => 'Liga Stavok',
        'linebet' => 'Linebet',
        'luckyblock' => 'Luckyblock',
        'marathon' => 'Marathon',
        'marathoncupis' => 'Marathon cupis',
        'megadice' => 'Megadice',
        'melbet' => 'MelbetRu',
        'mellstroy' => 'Mellstroy',
        'mostbet' => 'MostBet',
        'mostbetcupis' => 'MostBetCupis',
        'nordicbet' => 'Nordicbet',
        'olimpcupis' => 'Olimp Cupis',
        'olimpkz' => 'OlimpKZ',
        'olimpold' => 'Olimp OLD',
        'olybet' => 'Olybet',
        'paddy' => 'PaddyPower',
        'paribet' => 'Paribet',
        'pariby' => 'PariBY',
        'pariold' => 'PariMatch',
        'paricupis' => 'Parimatch Cupis',
        'pariuk' => 'PariMatchUK',
        'partypoker' => 'PartyPoker',
        'pinnacle' => 'Pinnacle',
        'pinup' => 'Pinup',
        'pinupcupis' => 'pinup cupis',
        'rainbet' => 'Rainbet',
        'razed' => 'Razed',
        'realbet' => 'Realbet',
        'red32' => 'red32',
        'riobet' => 'Riobet',
        'rollbit' => 'Rollbit',
        'roobet' => 'Roobet',
        'sbobet' => 'Sbobet',
        'shuflle' => 'Shuflle',
        'sol249' => 'Sol249',
        'sportingbet' => 'Sportingbet',
        'stake' => 'Stake',
        'stoiximan' => 'Stoiximan',
        'tether' => 'Tether',
        'topsport' => 'Topsport',
        'trustdice' => 'TrustDice',
        'ubet' => 'Ubet',
        'unibet' => 'Unibet',
        'vave' => 'Vave',
        'vbet' => 'Vbet',
        'weiss' => 'Weiss',
        'whale' => 'Whale',
        'wild' => 'Wild',
        'william' => 'WilliamHill',
        'winline' => 'Winlinebet',
        'winlinecupis' => 'Winline Cupis',
        'wsmcasino' => 'Wsmcasino',
        'zenit' => 'Zenit',
        'zulabet' => 'Zulabet',
    ],
    'bkMapping' => [
        'onewin' => '1WIN',
        'onexbet' => '1XBET',
        'onexbit' => '1XBIT',
        'onexstavka' => '1XSTAVKA',
        'sevenbet' => '7BET',
        'sport888' => '888SPORT',
        'astekbet' => 'ASTEKBET',
        'batery' => 'BATERY',
        'baterymobile' => 'BATERY.MOBILE',
        'bcgame' => 'BCGAME',
        'bet365' => 'BET365',
        'bet365au' => 'BET365.AU',
        'bet365it' => 'BET365.IT',
        'bet365test' => 'BET365TEST',
        'bet365es' => 'BET365.ES',
        'bet365gr' => 'BET365.GR',
        'bet365kz' => 'BET365.MX',
        'be365ru' => 'BET365.RU',
        'betandyou' => 'BETANDYOU',
        'betboom' => 'BETBOOM',
        'betboomcom' => 'BETBOOM.COM',
        'betcityby' => 'BETCITY.BY',
        'betcity' => 'BETCITY.CUPIS',
        'betfair' => 'BFSPORTSBOOK',
        'betfaires' => 'BETFAIR.ES',
        'betflip' => 'BETFLIP',
        'betfury' => 'BETFURY',
        'betiro' => 'BETIRO',
        'betpanda' => 'BETPANDA',
        'betplay' => 'BETPLAY',
        'betsafe' => 'BETSAFE',
        'betsson' => 'BETSSON',
        'betvictor' => 'BETVICTOR',
        'betway' => 'BETWAY',
        'betwaybe' => 'BETWAY.BE',
        'betwinner' => 'BETWINNER',
        'bitz' => 'BITZ',
        'bookmaker' => 'BOOKMAKERXYZ',
        'bwin' => 'BWIN',
        'bwinbe' => 'BWIN.BE',
        'bwincupis' => 'BWIN.CUPIS',
        'campobet' => 'CAMPOBET',
        'casinowinner' => 'CASINOWINNER',
        'chipsgg' => 'CHIPS.GG',
        'coinplay' => 'COINPLAY',
        'coinsgame' => 'COINSGAME',
        'crashino' => 'CRASHINO',
        'cryptocasino' => 'CRYPTOCASINO',
        'csgo500' => 'CSGO500',
        'dafabet' => 'DAFABET',
        'dbbet' => 'DOUBLEBET',
        'duel' => 'DUEL',
        'fairspin' => 'FAIRSPIN',
        'fansport' => 'FANSPORT',
        'favbet' => 'FAVBET',
        'fonru' => 'FONRU',
        'fonbet' => 'FONBET',
        'fonbetcupis' => 'FONBET.CUPIS',
        'fonbetby' => 'FONBET.BY',
        'foncupismobile' => 'FONBETCUPIS.MOBILE',
        'fonbetgr' => 'FONBET.GR',
        'fonbetkz' => 'FONBET.KZ',
        'fortunejack' => 'FORTUNEJACK',
        'gamdom' => 'GAMDOM',
        'jetbull' => 'JETBULL',
        'gamebookers' => 'GAMEBOOKERS',
        'grosvenor' => 'GROSVENOR',
        'ivibet' => 'IVIBET',
        'jbcom' => 'JBCOM',
        'jetton' => 'JETTON',
        'justbit' => 'JUSTBIT',
        'ladbrokes' => 'LADBROKES',
        'leon' => 'LEON',
        'leoncupis' => 'LEON.CUPIS',
        'ligastavok' => 'LIGASTAVOK',
        'linebet' => 'LINEBET',
        'luckyblock' => 'LUCKYBLOCK',
        'marathon' => 'MARATHON',
        'marathoncupis' => 'MARATHON.CUPIS',
        'megadice' => 'MEGADICE',
        'melbet' => 'MELBET.RU',
        'mellstroy' => 'MELLSTROY',
        'mostbet' => 'MOSTBET',
        'mostbetcupis' => 'MOSTBET.CUPIS',
        'nordicbet' => 'NORDICBET',
        'olimpcupis' => 'OLIMP.CUPIS',
        'olimpkz' => 'OLIMP.KZ',
        'olimpold' => 'OLIMP',
        'olybet' => 'OLYBET',
        'paddy' => 'PADDYPOWER',
        'paribet' => 'PARIBET',
        'pariby' => 'PARIMATCH.BY',
        'pariold' => 'PARIMATCH',
        'paricupis' => 'PARIMATCH.CUPIS',
        'pariuk' => 'PARIMATCH.UK',
        'partypoker' => 'PARTYPOKER',
        'pinnacle' => 'PINNACLE',
        'pinup' => 'PINUP',
        'pinupcupis' => 'PINUP.KZ',
        'rainbet' => 'RAINBET',
        'razed' => 'RAZED',
        'realbet' => 'REALBET',
        'red32' => '32RED',
        'riobet' => 'RIOBET',
        'rollbit' => 'ROLLBIT',
        'roobet' => 'ROOBET',
        'sbobet' => 'SBOBET',
        'shuflle' => 'SHUFFLE',
        'sol249' => 'SOLCASINO',
        'sportingbet' => 'SPORTINGBET',
        'stake' => 'STAKE',
        'stoiximan' => 'STOIXIMAN',
        'tether' => 'TETHER',
        'topsport' => 'TOPSPORT',
        'trustdice' => 'TRUSTDICE',
        'ubet' => 'UBET',
        'unibet' => 'UNIBET',
        'vave' => 'VAVE',
        'vbet' => 'VBET',
        'weiss' => 'WEISS',
        'whale' => 'WHALE',
        'wild' => 'WILD',
        'william' => 'WILLIAMHILL',
        'winline' => 'WINLINEBET',
        'winlinecupis' => 'WINLINE.CUPIS',
        'wsmcasino' => 'WSMCASINO',
        'zenit' => 'ZENIT',
        'zulabet' => 'ZULABET',
    ],
    'bkUrls' => [
        'onexbit' => [
            '"*://*.1xbit1.com/*"',
        ],
        'sevenbet' => [
            '"*://*.7bet.lt/*"',
        ],
        'astekbet' => [
            '"*://*.astekbet.com/*"',
        ],
        'bcgame' => [
            '"*://*.bc.game/*"',
        ],
        'bet365it' => [
            '"*://*.bet365.ee/*"',
        ],
        'bet365es' => [
            '"*://*.bet365.es/*"',
        ],
        'betandyou' => [
            '"*://*.betandyou.com/*"',
        ],
        'betboom' => [
            '"*://*.betboom.ru/*"',
            '"*://*.sport.betboom.ru/*"',
        ],
        'betboomcom' => [
            '"*://*.betboom.com/*"',
        ],
        'betcityby' => [
            '"*://*.betcity.by/*"',
        ],
        'betcity' => [
            '"*://*.betcity.ru/*"',
        ],
        'betfair' => [
            '"*://*.betfair.com/*"',
        ],
        'betfaires' => [
            '"*://*.betfair.es/*"',
        ],
        'betflip' => [
            '"*://*.betflip.io/*"',
            '"*://*.casobt-dlrh3csz.betsy.gg/*"',
        ],
        'betfury' => [
            '"*://*.betfury.ac/*"',
        ],
        'betiro' => [
            '"*://*.betiro.com/*"',
        ],
        'betpanda' => [
            '"*://*.betpanda.io/*"',
        ],
        'betplay' => [
            '"*://*.betplay.io/*"',
        ],
        'betsafe' => [
            '"*://*.betsafe.lt/*"',
        ],
        'betsson' => [
            '"*://*.betsson.com/*"',
        ],
        'betwinner' => [
            '"*://*.betwinner.com/*"',
        ],
        'bitz' => [
            '"*://*.bitz.io/*"',
        ],
        'bwincupis' => [
            '"*://*.bwin.ru/*", "*://*.pay.1cupis.ru/*"',
        ],
        'casinowinner' => [
            '"*://*.casinowinner.com/*"',
            '"*://*.bpsgameserver.com/*"',
        ],
        'chipsgg' => [
            '"*://*.chips.gg/*"',
        ],
        'coinplay' => [
            '"*://*.coinplay.com/*"',
        ],
        'coinsgame' => [
            '"*://*.coins.game/*"',
            '"*://*.sport4.coins.game/*"',
        ],
        'crashino' => [
            '"*://*.crashino.com/*"',
        ],
        'cryptocasino' => [
            '"*://*.cryptocasino.com/*"',
        ],
        'csgo500' => [
            '"*://*.csgo500.com/*"',
        ],
        'dbbet' => [
            '"*://*.db-bet.com/*"',
        ],
        'duel' => [
            '"*://*.duel.com/*"',
        ],
        'fairspin' => [
            '"*://*.fairspin.io/*"',
            '"*://*.fairspin-2-cei938sj.sportbook.work/*"',
        ],
        'favbet' => [
            '"*://*.favbet.com/*"',
        ],
        'fortunejack' => [
            '"*://*.fortunejack.com/*"',
        ],
        'gamdom' => [
            '"*://*.gamdom.vip/*"',
            '"*://*.sb.gamdom.onebittech.com/*"',
            '"*://*.recaptcha.net/*"',
        ],
        'jetbull' => [
            '"*://*.gamdom.io/*"',
            '"*://*.hub88b-ytuoyswg.betsy.gg/*"',
        ],
        'grosvenor' => [
            '"*://*.grosvenorcasinos.com/*"',
        ],
        'ivibet' => [
            '"*://*.ivibet.com/*"',
        ],
        'jbcom' => [
            '"*://*.jb.com/*"',
        ],
        'jetton' => [
            '"*://*.jetvegas.xyz/*"',
        ],
        'justbit' => [
            '"*://*.justbit.io/*"',
        ],
        'ligastavok' => [
            '"*://*.ligastavok.ru/*", "*://*.pay.1cupis.ru/*"',
        ],
        'linebet' => [
            '"*://*.linebet.com/*"',
        ],
        'luckyblock' => [
            '"*://*.luckyblock.top/*"',
        ],
        'marathon' => [
            '"*://*.marathonbet.by/*"',
        ],
        'marathoncupis' => [
            '"*://*.marathonbet.ru/*"',
        ],
        'megadice' => [
            '"*://*.megadice.com/*"',
        ],
        'melbet' => [
            '"*://*.melbet.ru/*"',
        ],
        'mellstroy' => [
            '"*://*.mell9778.com/*"',
        ],
        'nordicbet' => [
            '"*://*.nordicbet.com/*"',
        ],
        'olimpcupis' => [
            '"*://*.olimp.bet/*"',
        ],
        'olimpkz' => [
            '"*://*.olimpbet.kz/*", "*://ogixz.playmeagame.com/*"',
        ],
        'olimpold' => [
            '"*://*.olimp.com/*", "*://ogixz.playmeagame.com/*"',
        ],
        'olybet' => [
            '"*://*.olybet.lt/*"',
        ],
        'paddy' => [
            '"*://*.paddypower.com/*"',
        ],
        'pariby' => [
            '"*://*.pm.by/*"',
            '"*://*.iframes.pm.by/*"',
            '"*://*.smdvkm.live/*"',
        ],
        'pariold' => [
            '"*://*.parimatch.com/*"',
        ],
        'paricupis' => [
            '"*://*.parimatch.ru/*", "*://*.pay.1cupis.ru/*"',
        ],
        'pariuk' => [
            '"*://*.parimatch.co.uk/*"',
        ],
        'pinupcupis' => [
            '"*://*.pin-up.kz/*"',
        ],
        'rainbet' => [
            '"*://*.rainbet.com/*"',
        ],
        'razed' => [
            '"*://*.razed.com/*"',
        ],
        'realbet' => [
            '"*://*.realbet.io/*"',
        ],
        'red32' => [
            '"*://*.32red.com/*"',
        ],
        'rollbit' => [
            '"*://*.rollbit.com/*"',
        ],
        'sol249' => [
            '"*://*.sol.casino/*"',
            '"*://*.sport.sol.dgtnsptpub.com/*"',
        ],
        'stoiximan' => [
            '"*://*.en.stoiximan.gr/*"',
        ],
        'tether' => [
            '"*://*.tether.bet/*"',
            '"*://*.ta-tp-tetherbet-ed23ft6.turbostars.gg/?*"',
        ],
        'topsport' => [
            '"*://*.en.topsport.lt/*"',
            '"*://*.bc-sportsbook-spring.topsport.lt/*"',
        ],
        'ubet' => [
            '"*://*.ubet.kz/*"',
        ],
        'vave' => [
            '"*://*.vave.com/*"',
        ],
        'weiss' => [
            '"*://*.weiss4.bet/*", "*://*.weiss-dk37ncgy.sportbook.work/*"',
        ],
        'whale' => [
            '"*://*.whale.io/*"',
            '"*://*.telegramcasino-ni2mduvr4.betsy.gg/*"',
        ],
        'wild' => [
            '"*://*.wild.io/*"',
        ],
        'william' => [
            '"*://*.williamhill.com/*"',
        ],
        'wsmcasino' => [
            '"*://*.wsmcasino.vip/*"',
        ],
        'zenit' => [
            '"*://*.zenit.win/*"',
        ],
    ],
    'bkScripts' => [
        'onewin' => [
            'onewin.js',
        ],
        'onexbet' => [
            '1xbet.js',
        ],
        'onexbit' => [
            '1xothers.js',
        ],
        'onexstavka' => [
            '1xstavka.js',
            'cupis.js',
        ],
        'sevenbet' => [
            '7bet.js',
        ],
        'sport888' => [
            'sport888.js',
        ],
        'astekbet' => [
            '1xothers.js',
        ],
        'batery' => [
            'batery.js',
        ],
        'baterymobile' => [
            'batery.mobile.js',
        ],
        'bcgame' => [
            'bcgame.js',
        ],
        'bet365' => [
            'bet365.js',
        ],
        'bet365au' => [
            'bet365.js',
        ],
        'bet365it' => [
            'bet365.js',
        ],
        'bet365test' => [
            'bet365.js',
        ],
        'bet365es' => [
            'bet365.js',
        ],
        'bet365gr' => [
            'bet365.js',
        ],
        'bet365kz' => [
            'bet365.js',
        ],
        'be365ru' => [
            'bet365.js',
        ],
        'betandyou' => [
            '1xothers.js',
        ],
        'betboom' => [
            'betboom.js',
        ],
        'betboomcom' => [
            'betboom.js',
        ],
        'betcityby' => [
            'betcitycupis.js',
        ],
        'betcity' => [
            'betcitycupis.js',
        ],
        'betfair' => [
            'betfair.js',
        ],
        'betfaires' => [
            'betfair.js',
        ],
        'betflip' => [
            'betflip.js',
        ],
        'betfury' => [
            'betfury.js',
        ],
        'betiro' => [
            'fortunejack.js',
        ],
        'betpanda' => [
            'betpanda.js',
        ],
        'betplay' => [
            'betplay.js',
        ],
        'betsafe' => [
            'betsafe.js',
        ],
        'betsson' => [
            'betsson.js',
        ],
        'betvictor' => [
            'betvictor.js',
        ],
        'betway' => [
            'betway.js',
        ],
        'betwaybe' => [
            'betway.js',
        ],
        'betwinner' => [
            'betwinner.js',
        ],
        'bitz' => [
            'bitz.js',
        ],
        'bookmaker' => [
            'bookmaker.js',
        ],
        'bwin' => [
            'bwin.js',
        ],
        'bwinbe' => [
            'bwin.js',
        ],
        'bwincupis' => [
            'bwin.js',
            'cupis.js',
        ],
        'campobet' => [
            'riobet.js',
        ],
        'casinowinner' => [
            'betsson.js',
        ],
        'chipsgg' => [
            'chips.js',
        ],
        'coinplay' => [
            '1xothers.js',
        ],
        'coinsgame' => [
            'coinsgame.js',
        ],
        'crashino' => [
            'crashino.js',
        ],
        'cryptocasino' => [
            'cryptocasino.js',
        ],
        'csgo500' => [
            'csgo500.js',
        ],
        'dafabet' => [
            'dafabet.js',
        ],
        'dbbet' => [
            '1xothers.js',
        ],
        'duel' => [
            'duel.js',
        ],
        'fairspin' => [
            'weiss.js',
        ],
        'fansport' => [
            '1xbet.js',
        ],
        'favbet' => [
            'favbet.js',
        ],
        'fonru' => [
            'fonbetcupisru.js',
        ],
        'fonbet' => [
            'fonbet.js',
        ],
        'fonbetcupis' => [
            'fonbetcupis.js',
        ],
        'fonbetby' => [
            'fonbetby.js',
        ],
        'foncupismobile' => [
            'fonbetcupis.mobile.js',
        ],
        'fonbetgr' => [
            'fonbetcupis.js',
        ],
        'fonbetkz' => [
            'fonbetkz.js',
        ],
        'fortunejack' => [
            'fortunejack.js',
        ],
        'gamdom' => [
            'gamdom.js',
        ],
        'jetbull' => [
            'gamdom.js',
        ],
        'gamebookers' => [
            'gameparty.js',
        ],
        'grosvenor' => [
            'grosvenor.js',
        ],
        'ivibet' => [
            'ivibet.js',
        ],
        'jbcom' => [
            'jbcom.js',
        ],
        'jetton' => [
            'jetvegas.js',
        ],
        'justbit' => [
            'justbit.js',
        ],
        'ladbrokes' => [
            'ladbrokes.js',
        ],
        'leon' => [
            'leon.js',
        ],
        'leoncupis' => [
            'leon.js',
        ],
        'ligastavok' => [
            'ligastavok.js',
            'cupis.js',
        ],
        'linebet' => [
            '1xothers.js',
        ],
        'luckyblock' => [
            'luckyblock.js',
        ],
        'marathon' => [
            'marathon.js',
        ],
        'marathoncupis' => [
            'marathon.js',
        ],
        'megadice' => [
            'megadice.js',
        ],
        'melbet' => [
            'melbet.js',
        ],
        'mellstroy' => [
            'mellstroy.js',
        ],
        'mostbet' => [
            'mostobet.js',
        ],
        'mostbetcupis' => [
            'mostobet.js',
        ],
        'nordicbet' => [
            'betsson.js',
        ],
        'olimpcupis' => [
            'olimpCupis.js',
        ],
        'olimpkz' => [
            'olimpkz.js',
        ],
        'olimpold' => [
            'olimpParent.js',
        ],
        'olybet' => [
            'olybet.js',
        ],
        'paddy' => [
            'paddy.js',
        ],
        'paribet' => [
            'fonru.js',
        ],
        'pariby' => [
            'pariby.js',
        ],
        'pariold' => [
            'pariall.js',
        ],
        'paricupis' => [
            'pariall.js',
            'cupis.js',
        ],
        'pariuk' => [
            'pariall.js',
        ],
        'partypoker' => [
            'gameparty.js',
        ],
        'pinnacle' => [
            'pinnacle.js',
        ],
        'pinup' => [
            'pinup.js',
        ],
        'pinupcupis' => [
            'betboom.js',
        ],
        'rainbet' => [
            'rainbet.js',
        ],
        'razed' => [
            'razed.js',
        ],
        'realbet' => [
            'realbet.js',
        ],
        'red32' => [
            'unibet.js',
        ],
        'riobet' => [
            'riobet.js',
        ],
        'rollbit' => [
            'rollbit.js',
        ],
        'roobet' => [
            'roobet.js',
        ],
        'sbobet' => [
            'sbobet.js',
        ],
        'shuflle' => [
            'shuflle.js',
        ],
        'sol249' => [
            'solcasino.js',
        ],
        'sportingbet' => [
            'gameparty.js',
        ],
        'stake' => [
            'stake.js',
        ],
        'stoiximan' => [
            'stoiximan.js',
        ],
        'tether' => [
            'tether.js',
        ],
        'topsport' => [
            'topsport.js',
        ],
        'trustdice' => [
            'trustdice.js',
        ],
        'ubet' => [
            'betboom.js',
        ],
        'unibet' => [
            'unibet.js',
        ],
        'vave' => [
            'vave.js',
        ],
        'vbet' => [
            'vbet.js',
        ],
        'weiss' => [
            'weiss.js',
        ],
        'whale' => [
            'whale.js',
        ],
        'wild' => [
            'wild.js',
        ],
        'william' => [
            'william.js',
        ],
        'winline' => [
            'winline.js',
        ],
        'winlinecupis' => [
            'winlinecupis.js',
        ],
        'wsmcasino' => [
            'wsmcasino.js',
        ],
        'zenit' => [
            'zenit.js',
        ],
        'zulabet' => [
            'riobet.js',
        ],
    ],
    'bkAllFrames' => [
        'onexbit' => true,
        'sevenbet' => true,
        'astekbet' => true,
        'bcgame' => true,
        'bet365it' => true,
        'bet365es' => true,
        'betandyou' => true,
        'betboom' => true,
        'betboomcom' => true,
        'betfair' => true,
        'betfaires' => true,
        'betflip' => true,
        'betfury' => true,
        'betiro' => true,
        'betpanda' => true,
        'betplay' => true,
        'betsafe' => true,
        'betsson' => true,
        'betwinner' => true,
        'bitz' => true,
        'bwincupis' => true,
        'casinowinner' => true,
        'chipsgg' => true,
        'coinplay' => true,
        'coinsgame' => true,
        'crashino' => true,
        'cryptocasino' => true,
        'csgo500' => true,
        'dbbet' => true,
        'duel' => true,
        'fairspin' => true,
        'favbet' => true,
        'fortunejack' => true,
        'gamdom' => true,
        'jetbull' => true,
        'grosvenor' => true,
        'jbcom' => true,
        'jetton' => true,
        'justbit' => true,
        'linebet' => true,
        'luckyblock' => true,
        'marathon' => true,
        'marathoncupis' => true,
        'megadice' => true,
        'melbet' => true,
        'nordicbet' => true,
        'olimpcupis' => true,
        'olimpkz' => true,
        'olimpold' => true,
        'olybet' => true,
        'paddy' => true,
        'pariby' => true,
        'pariold' => true,
        'paricupis' => true,
        'pariuk' => true,
        'pinupcupis' => true,
        'rainbet' => true,
        'razed' => true,
        'realbet' => true,
        'red32' => true,
        'rollbit' => true,
        'sol249' => true,
        'stoiximan' => true,
        'tether' => true,
        'topsport' => true,
        'ubet' => true,
        'weiss' => true,
        'whale' => true,
        'william' => true,
        'wsmcasino' => true,
    ],
    'bkStartUrls' => [
        'onewin' => 'https://f1w-50.com/betting/live?p=c0hn',
        'onexbet' => 'https://1xlite-1099350.bar/ru/live',
        'onexbit' => 'https://1xbit.com',
        'onexstavka' => 'https://1xstavka.ru/live/',
        'sevenbet' => 'https://7bet.lt/en/live-betting',
        'sport888' => 'https://www.888sport.com/live-betting/',
        'astekbet' => 'https://astekbet.com/ru/live/',
        'batery' => 'https://batery-bets.in/sports',
        'baterymobile' => 'https://batery-bets.in/sports',
        'bcgame' => 'https://bc.game/sports',
        'bet365' => 'https://www.bet365.com/#/IP/',
        'bet365au' => 'https://www.bet365.com.au/#/IP/B1/',
        'bet365it' => 'https://www.bet365.it/#/IP/',
        'bet365test' => 'https://www.bet365.com/#/IP/',
        'bet365es' => 'https://www.bet365.es/#/IP/',
        'bet365gr' => 'https://www.bet365.gr/#/IP/',
        'bet365kz' => 'https://www.bet365.mx/#/IP/',
        'be365ru' => 'https://www.bet365.nl/#/IP/',
        'betandyou' => 'https://betandyou.com/ru/live/',
        'betboom' => 'https://betboom.ru/sport/live/',
        'betboomcom' => 'https://betboom.com/ru/sport/',
        'betcityby' => 'https://betcity.by/en/live',
        'betcity' => 'https://betcity.ru/en/live',
        'betfair' => 'https://www.betfair.com/sport/inplay',
        'betfaires' => 'https://www.betfair.es/sport/inplay',
        'betflip' => 'https://betflip.io/en-GB/home/sport/live',
        'betfury' => 'https://betfury.ac/sports',
        'betiro' => 'https://www.betiro.com/en/sports',
        'betpanda' => 'https://betpanda.io/en/sportsbook?bt-path=%2Flive',
        'betplay' => 'https://betplay.io/en/sportsbook',
        'betsafe' => 'https://www.betsafe.lt/en/live-betting',
        'betsson' => 'https://www.betsson.com/en/sportsbook/live/football',
        'betvictor' => 'https://www.betvictor.com/en-gb/sports',
        'betway' => 'https://sports.betway.com/en/sports/in-play',
        'betwaybe' => 'https://sports.betway.be/en/sports/in-play',
        'betwinner' => 'https://betwinner.com/ru/live/',
        'bitz' => 'https://bitz.io/sportsbook',
        'bookmaker' => 'https://bookmaker.xyz/polygon/sports',
        'bwin' => 'https://sports.bwin.com/en/sports/live/betting',
        'bwinbe' => 'https://livebetting.bwin.be/en/live',
        'bwincupis' => 'https://livebetting.bwin.ru/en/live',
        'campobet' => 'https://campobet7.com/en/sport/live',
        'casinowinner' => 'https://www.casinowinner.com/en/sport',
        'chipsgg' => 'https://chips.gg/sports?bt-path=/',
        'coinplay' => 'https://coinplay.com/ru/live',
        'coinsgame' => 'https://coins.game/sportss/?live',
        'crashino' => 'https://www.crashino.com/en/sports',
        'cryptocasino' => 'https://www.cryptocasino.com/sports',
        'csgo500' => 'https://csgo500.com/sports',
        'dafabet' => 'https://www.dafabet.com/en/dfgoal/sports/live',
        'dbbet' => 'https://db-bet.com/ru/live/',
        'duel' => 'https://duel.com/sports',
        'fairspin' => 'https://fairspin.io',
        'fansport' => 'https://slotisfaction.com/live',
        'favbet' => 'https://www.favbet.com/en/live/',
        'fonru' => 'https://www.fon.bet/live',
        'fonbet' => 'https://fonbet.com/live',
        'fonbetcupis' => 'https://fon.bet/live',
        'fonbetby' => 'https://fonbet.by/live',
        'foncupismobile' => 'https://fon.bet/live',
        'fonbetgr' => 'https://www.batery-bet.in/live',
        'fonbetkz' => 'https://www.fonbet.kz/live',
        'fortunejack' => 'https://fortunejack.com/crypto-sportsbook',
        'gamdom' => 'https://gamdom.vip/sports',
        'jetbull' => 'https://gamdom.io/esports',
        'gamebookers' => 'https://sports.gamebookers.com/en/sports/live/betting',
        'grosvenor' => 'https://www.grosvenorcasinos.com/sport/',
        'ivibet' => 'https://ivibet.com/live',
        'jbcom' => 'https://jb.com/sports',
        'jetton' => 'https://jetvegas.xyz/sportsbook',
        'justbit' => 'https://justbit.io/sports?bt-path=%2F',
        'ladbrokes' => 'https://sports.ladbrokes.com/in-play',
        'leon' => 'https://leon.bet/ru/live',
        'leoncupis' => 'https://www.leon.ru/stavki-live',
        'ligastavok' => 'https://ligastavok.ru/bets/live',
        'linebet' => 'https://linebet.com/ru/live/',
        'luckyblock' => 'https://www.luckyblock.top/en/sports',
        'marathon' => 'https://www.marathonbet.by/en/live/popular',
        'marathoncupis' => 'https://www.marathonbet.ru/live/',
        'megadice' => 'https://play.megadice.com/sports',
        'melbet' => 'https://melbet.ru/ru/sport',
        'mellstroy' => 'https://mell9778.com/betting',
        'mostbet' => 'https://mostbet.com/live',
        'mostbetcupis' => 'https://mostbet.ru/live',
        'nordicbet' => 'https://www.nordicbet.com/en/sportsbook/live/football',
        'olimpcupis' => 'https://www.olimp.bet/live',
        'olimpkz' => 'https://olimpbet.kz/betting',
        'olimpold' => 'https://olimp.com/betting',
        'olybet' => 'https://www.olybet.lt/sports/live',
        'paddy' => 'https://www.paddypower.com/inplay',
        'paribet' => 'https://www.pari.ru/live/',
        'pariby' => 'https://pm.by/en/sport/Live/page/',
        'pariold' => 'https://www.parimatch.com/live.html',
        'paricupis' => 'https://www.parimatch.ru/live.html',
        'pariuk' => 'https://www.parimatch.co.uk/live.html',
        'partypoker' => 'https://sports.partypoker.com/en/sports/live/betting',
        'pinnacle' => 'https://www.savedday.one/en/',
        'pinup' => 'https://pinup.bet/live-sports',
        'pinupcupis' => 'https://pin-up.kz/ru/sports/live',
        'rainbet' => 'https://rainbet.com/sportsbook',
        'razed' => 'https://www.razed.com/sports/',
        'realbet' => 'https://realbet.io/sports',
        'red32' => 'https://www.32red.com/sport',
        'riobet' => 'https://riobet.com/en/sport/live',
        'rollbit' => 'https://rollbit.com/sports',
        'roobet' => 'https://roobet.com/sports/live',
        'sbobet' => 'https://sbotop.com/sports',
        'shuflle' => 'https://shuffle.com/sports',
        'sol249' => 'https://sol.casino/en/sport',
        'sportingbet' => 'https://sports.sportingbet.com/en/sports/live/betting',
        'stake' => 'https://stake.com/sports/home',
        'stoiximan' => 'https://en.stoiximan.gr/live/',
        'tether' => 'https://tether.bet/betting',
        'topsport' => 'https://en.topsport.lt/live-tv',
        'trustdice' => 'https://trustdice.win/sports',
        'ubet' => 'https://ubet.kz/#live',
        'unibet' => 'https://www.unibet.com/betting',
        'vave' => 'https://vave.com/prematch?top=1',
        'vbet' => 'https://www.vbet.com/en/sports/pre-match/event-view/',
        'weiss' => 'https://weiss4.bet/sport/play',
        'whale' => 'https://whale.io/',
        'wild' => 'https://wild.io/sports',
        'william' => 'http://sports.williamhill.com/bet/en-gb/betlive/all',
        'winline' => 'https://wlnbet2.com',
        'winlinecupis' => 'https://winline.ru',
        'wsmcasino' => 'https://www.wsmcasino.vip/en/sports',
        'zenit' => 'https://zenit.win/live',
        'zulabet' => 'https://zulabet1.com/en/sport/live',
    ],
    'bkUrlCheck' => [
        'onexbit' => 'https://1xbit.com',
        'sevenbet' => '7bet.lt/en/live-betting',
        'astekbet' => 'astekbet.com',
        'bcgame' => 'bc.game',
        'bet365it' => 'bet365.ee',
        'bet365es' => 'bet365.es',
        'betandyou' => 'betandyou.com',
        'betboom' => 'betboom.ru',
        'betboomcom' => 'betboom.com',
        'betcityby' => 'betcity.by',
        'betcity' => 'betcity.ru',
        'betfair' => 'betfair.com',
        'betfaires' => 'betfair.es',
        'betflip' => 'betflip.io',
        'betfury' => 'betfury.ac',
        'betiro' => 'betiro.com',
        'betpanda' => 'betpanda.io',
        'betplay' => 'betplay.io',
        'betsafe' => 'betsafe.lt/en/live-betting',
        'betsson' => 'betsson.com',
        'betwinner' => 'betwinner.com',
        'bitz' => 'bitz.io',
        'bwincupis' => 'bwin.ru',
        'casinowinner' => 'casinowinner.com',
        'chipsgg' => 'chips.gg',
        'coinplay' => 'coinplay.com',
        'coinsgame' => 'coins.game',
        'crashino' => 'crashino.com',
        'cryptocasino' => 'cryptocasino.com',
        'csgo500' => 'csgo500.com',
        'dbbet' => 'db-bet.com',
        'duel' => 'duel.com',
        'fairspin' => 'fairspin.io',
        'favbet' => 'favbet.com',
        'fortunejack' => 'fortunejack.com',
        'gamdom' => 'gamdom.vip',
        'jetbull' => 'gamdom.io',
        'grosvenor' => 'grosvenorcasinos.com',
        'ivibet' => 'ivibet.com',
        'jbcom' => 'jb.com',
        'jetton' => 'jetvegas.xyz',
        'justbit' => 'justbit.io',
        'ligastavok' => 'ligastavok.ru',
        'linebet' => 'linebet.com',
        'luckyblock' => 'luckyblock.top',
        'marathon' => 'marathonbet.by',
        'marathoncupis' => 'marathonbet.ru',
        'megadice' => 'play.megadice.com',
        'melbet' => 'melbet.ru',
        'mellstroy' => 'mell9778.com',
        'nordicbet' => 'nordicbet.com',
        'olimpcupis' => 'olimp.bet',
        'olimpkz' => 'olimpbet.kz',
        'olimpold' => 'olimp.com',
        'olybet' => 'olybet.lt',
        'paddy' => 'paddypower.com',
        'pariby' => 'pm.by',
        'pariold' => 'parimatch.com',
        'paricupis' => 'parimatch.ru',
        'pariuk' => 'parimatch.co.uk',
        'pinupcupis' => 'pin-up.kz',
        'rainbet' => 'rainbet.com',
        'razed' => 'razed.com',
        'realbet' => 'realbet.io',
        'red32' => '32red.com',
        'rollbit' => 'rollbit.com',
        'sol249' => 'sol.casino',
        'stoiximan' => 'en.stoiximan.gr',
        'tether' => 'tether.bet',
        'topsport' => 'en.topsport.lt',
        'ubet' => 'ubet.kz',
        'vave' => 'vave.com',
        'weiss' => 'weiss4.bet',
        'whale' => 'whale.io',
        'wild' => 'wild.io',
        'william' => 'williamhill.com',
        'wsmcasino' => 'wsmcasino.vip',
        'zenit' => 'zenit.win',
    ],
    'bkLiveUrl' => [
        'onewin' => '/betting/live',
        'onexbet' => '/live/',
        'onexstavka' => '/live/',
        'sport888' => '/live-betting',
        'batery' => '/sports',
        'baterymobile' => '/sports',
        'bet365' => '/#/IP/',
        'bet365au' => '/#/IP/B1/',
        'bet365test' => '/#/IP/',
        'bet365gr' => '/#/IP/',
        'bet365kz' => '/#/IP/',
        'be365ru' => '/#/IP/',
        'betvictor' => 'https://www.betvictor.com/en-gb/sports',
        'betway' => '/en/sports/in-play',
        'betwaybe' => '/en/sports/in-play',
        'bookmaker' => 'polygon/sports',
        'bwin' => '/en/sports/live/betting',
        'bwinbe' => '/en/live',
        'campobet' => 'en/sport/live',
        'dafabet' => '/en/dfgoal/sports/live',
        'fansport' => '/live/',
        'fonru' => '/live',
        'fonbet' => '/live',
        'fonbetcupis' => '/live',
        'fonbetby' => '/live',
        'foncupismobile' => '/live',
        'fonbetgr' => '/live',
        'fonbetkz' => '/live',
        'gamebookers' => 'en/sports/live/betting',
        'ladbrokes' => 'https://sports.ladbrokes.com/in-play',
        'leon' => '/live',
        'leoncupis' => '/stavki-live',
        'mostbet' => '/live',
        'mostbetcupis' => 'https://mostbet.ru/live',
        'paribet' => '/live/',
        'partypoker' => 'en/sports/live/betting',
        'pinnacle' => '/en/',
        'pinup' => '/live-sports/',
        'riobet' => '/en/sport/live',
        'roobet' => '/sports/live',
        'sbobet' => 'https://sbotop.com/sports',
        'shuflle' => '/sports',
        'sportingbet' => 'en/sports/live/betting',
        'stake' => '/sports/live/soccer',
        'trustdice' => 'sports/live/soccer',
        'unibet' => '/betting',
        'vbet' => '/en/sports/pre-match/event-view/',
        'winline' => '/now/',
        'winlinecupis' => '/now/',
        'zulabet' => '/en/sport/live',
    ],
    'bkAutoload' => [
        'onewin' => true,
        'onexbet' => true,
        'onexstavka' => true,
        'sport888' => true,
        'batery' => true,
        'baterymobile' => true,
        'bet365' => true,
        'bet365au' => true,
        'bet365test' => true,
        'bet365gr' => true,
        'bet365kz' => true,
        'be365ru' => true,
        'betvictor' => true,
        'betway' => true,
        'betwaybe' => true,
        'bookmaker' => true,
        'bwin' => true,
        'bwinbe' => true,
        'campobet' => true,
        'dafabet' => true,
        'fansport' => true,
        'fonru' => true,
        'fonbet' => true,
        'fonbetcupis' => true,
        'fonbetby' => true,
        'foncupismobile' => true,
        'fonbetgr' => true,
        'fonbetkz' => true,
        'gamebookers' => true,
        'ladbrokes' => true,
        'leon' => true,
        'leoncupis' => true,
        'mostbet' => true,
        'mostbetcupis' => true,
        'paribet' => true,
        'partypoker' => true,
        'pinnacle' => true,
        'pinup' => true,
        'riobet' => true,
        'roobet' => true,
        'sbobet' => true,
        'shuflle' => true,
        'sportingbet' => true,
        'stake' => true,
        'trustdice' => true,
        'unibet' => true,
        'vbet' => true,
        'winline' => true,
        'winlinecupis' => true,
        'zulabet' => true,
    ],
    'bkAutoCheck' => [
        'onewin' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"f1w-50.com/betting/"}],"valid":true}',
        'onexbet' => '{"condition":"OR","rules":[{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"1xBET"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"1xBET"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"1XBET"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"1xbet.com"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"1xBet"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"1хбет"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"1xbet.kz"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"ua1xbet.com"},{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"user/accountverify/"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"1x"}]},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"br.1xbet.com"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"1xlite-93399.world"}],"valid":true}',
        'onexstavka' => '{"condition":"OR","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"pay.1cupis.ru/refill"},{"condition":"OR","rules":[{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"1xСтавка"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"1хСтавка"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"1xstavka.ru"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"1xStavka"}]},{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"user/accountverify"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"1x"}]}],"valid":true}',
        'sport888' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"888sport.ro"}],"valid":true}',
        'batery' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"batery-bets.in"}],"valid":true}',
        'baterymobile' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"batery-bets.in"}],"valid":true}',
        'bet365' => '{"condition":"OR","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"bet365.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"bet365.de"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"bet365.mx"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"288365.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"allsport365.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"bet365.ee"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"365sport365.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"365365040.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"365365304.com"}],"valid":true}',
        'bet365au' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"bet365.com.au"}],"valid":true}',
        'bet365test' => '{"condition":"OR","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"bet365.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"365838.com"}],"valid":true}',
        'bet365gr' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"bet365.gr"}],"valid":true}',
        'bet365kz' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"bet365.mx"}],"valid":true}',
        'be365ru' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"bet365.nl"}],"valid":true}',
        'betvictor' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"betvictor.com"}],"valid":true}',
        'betway' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"betway."}],"valid":true}',
        'betwaybe' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".betway."}],"valid":true}',
        'bookmaker' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"bookmaker.xyz"}],"valid":true}',
        'bwin' => '{"condition":"OR","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".bwin."},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".bwin.es"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".bwin.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"p.iivt.com"}],"valid":true}',
        'bwinbe' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".bwin."}],"valid":true}',
        'campobet' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".campobet."}],"valid":true}',
        'dafabet' => '{"condition":"OR","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"dafabet.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"dfbertuah.com"}],"valid":true}',
        'fansport' => '{"condition":"AND","rules":[{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"Live ставки на спорт"}],"valid":true}',
        'fonru' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"fon.bet"}],"valid":true}',
        'fonbet' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"fonbet.com"}],"valid":true}',
        'fonbetcupis' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"fon.bet"}],"valid":true}',
        'fonbetby' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"fonbet.by"}],"valid":true}',
        'foncupismobile' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"fon.bet"}],"valid":true}',
        'fonbetgr' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"batery-bet."}],"valid":true}',
        'fonbetkz' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"fonbet.kz"}],"valid":true}',
        'gamebookers' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".gamebookers."}],"valid":true}',
        'ladbrokes' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"ladbrokes.com"}],"valid":true}',
        'leon' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"leon.bet/"},{"condition":"OR","rules":[{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"Leon"},{"condition":"AND","rules":[{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"Актуальное зеркало"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"БК Леон"}]}]}],"valid":true}',
        'leoncupis' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"leon.ru"}],"valid":true}',
        'mostbet' => '{"condition":"OR","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"mostbet.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"omthocmb.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"nk3kbbmb.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"cciylbmb.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"oqsh1vmb.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"lqwopzmb.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"amkmbwmb.com"}],"valid":true}',
        'mostbetcupis' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"mostbet.ru"}],"valid":true}',
        'paribet' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"pari.ru"}],"valid":true}',
        'partypoker' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".partypoker."}],"valid":true}',
        'pinnacle' => '{"condition":"OR","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"savedday.one"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"pinnacle.com"}],"valid":true}',
        'pinup' => '{"condition":"OR","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"sport.pin-up340.com/SportsBook/Overview"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":" pin-up78x.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"pin-up04s.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"pin-up72h.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"pin-up05a.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"pin-up70b.com"}],"valid":true}',
        'riobet' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".riobet."}],"valid":true}',
        'roobet' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"roobet.com"}],"valid":true}',
        'sbobet' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"sbotop.com"}],"valid":true}',
        'shuflle' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"shuffle.com"}],"valid":true}',
        'sportingbet' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".sportingbet."}],"valid":true}',
        'stake' => '{"condition":"OR","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"stake.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"stake1038.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"stake1069.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"stake.ceo"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"challenges.cloudflare.com"}],"valid":true}',
        'trustdice' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"trustdice.win"}],"valid":true}',
        'unibet' => '{"condition":"OR","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"unibet.com"},{"condition":"AND","rules":[{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"Unibet"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"Online Betting and Live Betting"}]},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"unibet.be"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"unibet.co.uk"}],"valid":true}',
        'vbet' => '{"condition":"OR","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".vbet.com"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".vbet.de"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".vbet.am"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".vbet.ua"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".vbet.co.uk"},{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".dafabet.co.uk"}],"valid":true}',
        'winline' => '{"condition":"OR","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"winline."},{"condition":"AND","rules":[{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"Винлайн"},{"condition":"OR","rules":[{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"Ставки на спорт онлайн!"},{"id":"title","field":"title","type":"string","input":"text","operator":"contains","value":"Онлайн ставки на спорт!"}]}]}],"valid":true}',
        'winlinecupis' => '{"condition":"OR","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":"winline.ru"}],"valid":true}',
        'zulabet' => '{"condition":"AND","rules":[{"id":"href","field":"href","type":"string","input":"text","operator":"contains","value":".zulabet."}],"valid":true}',
    ],
    'bkCheckSpecial' => [
        'pinup' => true,
        'vbet' => true,
    ],
];
